### ISSUE TITLE
Context menu scaling doesn't follow main screen (or system-level) scaling (Linux)

### ISSUE THREAD

**Issue by gaydenko** [sjoerdvankreel/firefly-synth#3] opened 2024-03-10 10:38 UTC
Hi,
Sorry, I'm here again with scaling problem. Context menu (as well, for example, "Are you sure" dialog on Init click) doesn't follow main screen scaling. Have tried both vst3 and clap versions. These dialogs don't follow system scaling also (200% at my case). 
![ff-diaolog-scaling](https://github.com/sjoerdvankreel/firefly-synth/assets/3740016/16e9b2b0-ff03-4ac7-bd51-19fce578ff2a)

**Comment by sjoerdvankreel** [comment] 2024-03-10 17:17
<< Context menu doesn't follow main screen scaling

Actually most of them do, it's just the undo/redo menu that doesn't react to ui scale? Or am I missing others?

<< "Are you sure" dialog on Init click

Those are operating system native message boxes. I don't think there's an easy way to have them react to the plugin editor window scale, other then convert them to JUCE message boxes.

<< These dialogs don't follow system scaling also

Correct. I did not implement DPI awareness. It's a nice feature though, added to the backlog.

**Comment by gaydenko** [comment] 2024-03-10 17:33
> Actually most of them do, it's just the undo/redo menu that doesn't react to ui scale?

You are right. Couldn't say about all places, but other context menu I have tried (matrix cells,  knobs, sliders...) are Ok.


> I don't think there's an easy way to have them react to the plugin editor window scale, other then convert them to JUCE message boxes.

I see my use case could be marginal, and  the issue  is a stopper just for me.

**Comment by sjoerdvankreel** [comment] 2024-03-10 17:53
<< You are right. Couldn't say about all places, but other context menu I have tried (matrix cells, knobs, sliders...) are Ok.

Fixed the undo menu scaling in v1.2.3.

<< I see my use case could be marginal, and the issue is a stopper just for me.

I could swap out the native message boxes for juce built-in message boxes. Then they not only react to scaling but also to the main window theme (colors, fonts, etc). It's a nice-to-have, bit of work, but not too bad. Of course then it would only be logical if I also did the same for the file pickers.

Have to ask though, are those small "are you sure" popups really a stopper ? Do they prevent you from comfortably using the plugin in any way ?

**Comment by gaydenko** [comment] 2024-03-10 18:34
> Fixed the undo menu scaling in v1.2.3.

Thanks, have verified, it's Ok now.




> I could swap out the native message boxes for juce built-in message boxes.

It would be great.



> the same for the file pickers

I'd want to emphasize Load/Save dialog have got system look and are Ok in terms of scaling as opposed to Init dialog.

![ff-file-dialog](https://github.com/sjoerdvankreel/firefly-synth/assets/3740016/22025979-b425-4eb7-b729-2e0712084349)
![ff-init-dialog](https://github.com/sjoerdvankreel/firefly-synth/assets/3740016/857da846-b1e4-4c18-a0bc-6af7d9ec2dba)

**Comment by sjoerdvankreel** [comment] 2024-03-10 18:44
<< I'd want to emphasize Load/Save dialog have got system look and are Ok in terms of scaling as opposed to Init dialog.

Ah! That's good to know. Maybe it works a bit different on windows vs linux:
![image](https://github.com/sjoerdvankreel/firefly-synth/assets/2647549/d115a964-9c08-4bd6-b5ad-8f55544de4a3)

A quick fix would be to just turn the native message boxes into juce message boxes, so they pick up scaling, but i will forego theming for now. Judging by your screenshot, the linux version already falls back to juce message boxes. Probably the native message box is swapped out for a generic one on linux. On windows it looks like this:

![image](https://github.com/sjoerdvankreel/firefly-synth/assets/2647549/ce362f19-a6fb-4f73-aaf0-700137dab39d)

That'd be a quick and easy way to have scaleable dialog boxes. Will look into it.

**Comment by sjoerdvankreel** [comment] 2024-03-10 21:14
Fixed the dialog box scaling in 1.2.4.
I didn't touch the file choosers, so they continue to behave as-is.
Just the "are you sure" and a couple other message boxes.
Can you confirm ?

![image](https://github.com/sjoerdvankreel/firefly-synth/assets/2647549/3ce26d67-81d4-4b3b-8552-4704db1459e5)

![image](https://github.com/sjoerdvankreel/firefly-synth/assets/2647549/3b04d6f8-9964-4636-96fa-863639ff594f)

**Comment by gaydenko** [comment] 2024-03-10 21:30
> Can you confirm ?

I can. Sincerely thanks,  all known scaling issues are resolved for me.

**Comment by sjoerdvankreel** [comment] 2024-03-10 21:53
Great! I'm closing this issue.
Let me know if you run into any other problems.

**Closed by sjoerdvankreel** 2024-03-10 21:53 UTC
